#!/bin/bash -e

if [ ! -f /etherpad/SESSIONKEY.txt ]; then
  pwgen -s 40 -1 > /etherpad/SESSIONKEY.txt
fi

if [ ! -f /etherpad/APIKEY.txt ]; then
  pwgen -s 40 -1 > /etherpad/APIKEY.txt
fi

chown -Rh etherpad:etherpad /etherpad/var

export NODE_ENV=production

cd /etherpad
exec chpst -u etherpad:etherpad /usr/bin/node /etherpad/node_modules/ep_etherpad-lite/node/server.js 2>&1
